- name: Set the Kubernetes Context
  shell: "kubectl config set-context tools"

- name: Set postgresql service name
  set_fact:
    postgresql_service_name: "{{ kubernetes_deployment_name }}-postgresql"
  when: "pg_hostname is not defined or pg_hostname == ''"
